services:
  web:
    image: nginx:1.17.1
    container_name: web-${COMPOSE_PROJECT_NAME}
    ports:
      - ${SERVER_PORT}:80
    restart: ${RESTART_POLICY}
    volumes:
      - .:/app
      - .docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    environment:
      VIRTUAL_HOST: "${VIRTUAL_HOST}"
      LETSENCRYPT_HOST: "${VIRTUAL_HOST}"
    depends_on:
      - php
    networks:
      - default
      - nginx-proxy

  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: php-${COMPOSE_PROJECT_NAME}
    restart: ${RESTART_POLICY}
    volumes:
      - .:/app
      - .docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db-${COMPOSE_PROJECT_NAME}
    restart: ${RESTART_POLICY}
    command:
      - "--server-id=1"
      - "--log-bin=mysql-bin-1.log"
      - "--default-authentication-plugin=mysql_native_password"
      - "--lower_case_table_names=1"
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql

  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-${COMPOSE_PROJECT_NAME}
    restart: ${RESTART_POLICY}
    volumes:
      - .docker/phpmyadmin/php.ini:/usr/local/etc/php/php.ini
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - ${PHPMYADMIN_PORT}:80
    links:
      - db

volumes:
  db_data:

networks:
  nginx-proxy:
    external: true
