controllers:
    resource: ../src/Controller/
    type: attribute

product_controller:
    resource: ../src/Controller/ProductController.php
    type: annotation

auth_controller:
    resource: ../src/Controller/AuthController.php
    type: annotation